name: GithubActionsDevelopWindows

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

env:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug_Server'
  ciSuffix: CI.${{ github.run_number }}
  output: ${{ github.workspace }}\package
  project: 'BMB\BMB.csproj'

jobs:

  buildanddeploy:

    runs-on: windows-latest

    steps:

    - name: Get the branch
      id: get_branch
      run: echo ::set-output name=branch::${GITHUB_REF/refs\/heads\//}
      shell: bash

    - name: Get the pullrequest
      id: get_pullrequest
      run: echo ::set-output name=pullrequest::${GITHUB_REF/refs\/pull\//}
      shell: bash

    - name: Get the tag
      id: get_tag
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      shell: bash

    - name: Show branch name Ꙫ
      run: echo "GitHub indicates that this is a branch push request of ${{steps.get_branch.outputs.branch}}"
      if: contains(github.ref, 'refs/heads')

    - name: Show PR name Ꙫ
      run: echo "GitHub indicates that this is a pull request called ${{steps.get_pullrequest.outputs.pullrequest}}"
      if: contains(github.ref, 'refs/pull')

    - name: Show Tag name Ꙫ
      run: echo "GitHub indicates that this is a tag creation with ${{steps.get_tag.outputs.tag}}"
      if: contains(github.ref, 'refs/tag')


    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2


    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302

    - name: Display CI suffix Ꙫ
      run: echo ${env:ciSuffix}

    - name: Build 🔧
      run: dotnet publish --configuration ${env:buildConfiguration} ${env:project}
