name: GithubActionsDevelopWindows

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

env:
  buildConfiguration: 'Release'
  output: ${{ github.workspace }}\package
  project: 'BMB\BMB.csproj'

jobs:

  buildanddeploy:

    runs-on: windows-latest

    steps:

    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302

    - name: Build 🔧
      run: dotnet publish --configuration ${env:buildConfiguration} ${env:project}
